config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/oauth_application.rb
# frozen_string_literal: true

class OauthApplication < ApplicationRecord
end

app/models/oauth_grant.rb
# frozen_string_literal: true

class OauthGrant < ApplicationRecord
end

app/models/oauth_token.rb
# frozen_string_literal: true

class OauthToken < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :posts

  # hacking around not having profile separated from user model nor concept of usre name.
  def name
    email.split("@").first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def authenticate_user!
    rodauth.session_value || super
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :require_read_access, only: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    account = current_user || current_oauth_account
    @posts = account.posts.all
    respond_to do |format|
      format.html
      format.json { render json: @posts.to_json }
    end
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      account = current_account || current_oauth_account
      @post = account.posts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end

    def require_read_access
      return require_authentication unless request.authorization && request.authorization.start_with?("Bearer")

      rodauth.require_oauth_authorization("posts.read")
    end
end

app/controllers/rodauth_controller.rb
class RodauthController < ApplicationController
  # used by Rodauth for rendering views, CSRF protection, and running any
  # registered action callbacks and rescue_from handlers
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/application/_flash.html.erb
<% if notice %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>

<% if alert %>
  <div class="alert alert-danger"><%= alert %></div>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light border-bottom mb-4">
  <div class="container">
    <%= link_to "Rails App", root_path, class: "navbar-brand" %>

    <div class="navbar-collapse">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Posts", posts_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item <%= "active" unless current_page?(rodauth.oauth_applications_path) %>">
            <%= link_to_unless_current "Client Applications", rodauth.oauth_applications_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
    <% if user_signed_in? %>
      <div class="dropdown">
        <%= link_to current_user.email, "#", class: "btn btn-info dropdown-toggle", data: { toggle: "dropdown" } %>
        <div class="dropdown-menu dropdown-menu-right">
          <%= link_to "Change password", edit_user_password_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </div>
    <% else %>
      <div>
        <%= link_to "Sign in", new_user_session_path, class: "btn btn-outline-primary" %>
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</nav>

app/views/home/index.html.erb
<div class="jumbotron bg-light border">
  <h1 class="display-4">Rodauth App</h1>
  <p class="lead">This is a simple Rails application with basic posts CRUD and Bootstrap installed.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render "navbar" %>

    <div class="container">
      <%= render "flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post, class: "btn btn-secondary" %>
<%= link_to 'Back', posts_path, class: "btn btn-link" %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td>
          <%= link_to 'Show', post, class: "btn btn-secondary" %>
          <%= link_to 'Edit', edit_post_path(post), class: "btn btn-warning" %>
          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path, class: "btn btn-success" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>

<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-warning" %>
<%= link_to 'Back', posts_path, class: "btn btn-link" %>

app/views/rodauth/authorize.html.erb
<%= form_tag rodauth.authorize_path, method: :post do %>
  <% if rodauth.oauth_application[rodauth.oauth_applications_logo_uri_column] %>
    <%= image_tag rodauth.oauth_application[rodauth.oauth_applications_logo_uri_column] %>
  <% end %>
  <p class="lead"><%= rodauth.authorize_page_lead(name: link_to(rodauth.oauth_application[rodauth.oauth_applications_name_column],  rodauth.oauth_application[rodauth.oauth_applications_homepage_url_column])).html_safe %></p>

  <div class="list-group">
    <% if rodauth.oauth_application[rodauth.oauth_applications_tos_uri_column] %>
      <%= link_to rodauth.oauth_applications_tos_uri_label, rodauth.oauth_application[rodauth.oauth_applications_tos_uri_column], class: "list-group-item" %>
    <% end %>
    <% if rodauth.oauth_application[rodauth.oauth_applications_policy_uri_column] %>
      <%= link_to rodauth.oauth_applications_policy_uri_label, rodauth.oauth_application[rodauth.oauth_applications_policy_uri_column], class: "list-group-item" %>
    <% end %>
  </div>

  <% if rodauth.oauth_application[rodauth.oauth_applications_contacts_column] %>
    <div class="list-group">
      <h3 class="display-6"><%= rodauth.oauth_applications_contacts_label %></h3>
      <% rodauth.oauth_application[rodauth.oauth_applications_contacts_column].split(/ +/).each do |contact| %>
        <div class="list-group-item"><%= contact %></div>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <h1 class="display-6"><%= rodauth.oauth_grants_scopes_label %></h1>

    <% rodauth.authorize_scopes.each do |scope| %>
      <div class="form-check">
        <%= check_box_tag "scope[]", scope, id: scope, class: "form-check-input" %>
        <%= label_tag scope, scope, class: "form-check-label" %>
      </div>
    <% end %>
    <%= hidden_field_tag :client_id, params[:client_id] %>
    <% %i[access_type response_type response_mode state redirect_uri].each do |oauth_param| %>
      <% if params[oauth_param] %>
        <%= hidden_field_tag oauth_param,  params[oauth_param] %>
      <% end %>
    <% end %>
    <% if rodauth.features.include?(:oauth_resource_indicators) && rodauth.resource_indicators %>
      <% rodauth.resource_indicators.each do |resource| %>
        <%= hidden_field_tag "resource", resource %>
      <% end %>
    <% end %>
    <% if rodauth.features.include?(:oauth_pkce) %>
      <% if params[:code_challenge] %>
        <%= hidden_field_tag :code_challenge,  params[:code_challenge] %>
      <% end %>
      <% if params[:code_challenge_method] %>
        <%= hidden_field_tag :code_challenge_method,  params[:code_challenge_method] %>
      <% end %>
    <% end %>
    <% if rodauth.features.include?(:oidc) %>
      <% if params[:nonce] %>
        <%= hidden_field_tag :nonce,  params[:nonce] %>
      <% end %>
      <% if params[:ui_locales] %>
        <%= hidden_field_tag :ui_locales,  params[:ui_locales] %>
      <% end %>
      <% if params[:claims_locales] %>
        <%= hidden_field_tag :claims_locales,  params[:claims_locales] %>
      <% end %>
      <% if params[:acr_values] %>
        <%= hidden_field_tag :acr,  params[:acr_values] %>
      <% end %>
    <% end %>
  </div>
 <p class="text-center">
    <%= submit_tag rodauth.oauth_authorize_button, class: "btn btn-outline-primary" %>
    <%= link_to rodauth.oauth_cancel_button, "#{rodauth.redirect_uri}?error=access_denied&error_description=The+resource+owner+or+authorization+server+denied+the+request#{"&state=\#{rodauth.state}" if params[:state] }", class: "btn btn-outline-danger" %>
  </p>
<% end %>

app/views/rodauth/new_oauth_application.html.erb
<h2><%= rodauth.new_oauth_application_page_title %></h2>
<%= form_tag rodauth.oauth_applications_path, method: :post, class: "form-horizontal" do %>
  <%= rodauth.field_error('scope') %>
  <div class="form-group">
    <%= label_tag "name", rodauth.oauth_applications_name_label %>
    <%= text_field_tag "name", rodauth.param('name'), class: "form-control#{' is-invalid' if rodauth.field_error('name')}" %>
    <%= rodauth.field_error('name') %>
  </div>
  <div class="form-group">
    <%= label_tag "description", rodauth.oauth_applications_description_label %>
    <%= text_field_tag "description", rodauth.param('description'), class: "form-control#{' is-invalid' if rodauth.field_error('description')}" %>
    <%= rodauth.field_error('description') %>
  </div>
  <div class="form-group">
    <%= label_tag "homepage_url", rodauth.oauth_applications_homepage_url_label %>
    <%= text_field_tag "homepage_url", rodauth.param('homepage_url'), id: "homepage-url", class: "form-control#{' is-invalid' if rodauth.field_error('homepage_url')}" %>
    <%= rodauth.field_error('homepage_url') %>
  </div>
  <div class="form-group">
    <%= label_tag "redirect_uri", rodauth.oauth_applications_redirect_uri_label %>
    <%= text_field_tag "redirect_uri", rodauth.param('redirect_uri'), id: "redirect-uri", class: "form-control#{' is-invalid' if rodauth.field_error('redirect_uri')}" %>
    <%= rodauth.field_error('redirect_uri') %>
  </div>
  <div class="form-group">
    <%= label_tag "client_secret", rodauth.oauth_applications_client_secret_label %>
    <%= text_field_tag "client_secret", rodauth.param('client_secret'), id: "client-secret", class: "form-control#{' is-invalid' if rodauth.field_error('client_secret')}" %>
    <%= rodauth.field_error('client_secret') %>
  </div>
  <% rodauth.oauth_application_scopes.each do |scope| %>
    <div class="form-check">
      <%= check_box_tag "scopes[]", scope, id: scope, class: "form-check-input" %>
      <%= scope %>
    </div>
  <% end %>
  <div class="form-group">
    <%= submit_tag rodauth.oauth_application_button, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rodauth/oauth_application.html.erb
<% oauth_application = rodauth.scope.instance_variable_get(:@oauth_application) %>
<div>
  <h2><%= oauth_application[rodauth.oauth_applications_name_column] %></h2>

  <dl>
    <dt><%= rodauth.oauth_applications_description_label %>: </dt>
    <dd><%= oauth_application[rodauth.oauth_applications_description_column] %></dd>
    <dt><%= rodauth.oauth_applications_homepage_url_label %>: </dt>
    <dd><%= oauth_application[rodauth.oauth_applications_homepage_url_column] %></dd>
    <dt><%= rodauth.oauth_applications_client_id_label %>: </dt>
    <dd><%= oauth_application[rodauth.oauth_applications_client_id_column] %></dd>
    <dt><%= rodauth.oauth_applications_redirect_uri_label %>: </dt>
    <dd><%= oauth_application[rodauth.oauth_applications_redirect_uri_column] %></dd>
    <dt><%= rodauth.oauth_applications_scopes_label %>: </dt>
    <dd><%= oauth_application[rodauth.oauth_applications_scopes_column] %></dd>
    <% if rodauth.features.include?(:oauth_jwt) %>
      <% if oauth_application[rodauth.oauth_applications_jwks_column] %>
        <dt><%= rodauth.oauth_applications_jwks_label %>: </dt>
        <dd><%= oauth_application[rodauth.oauth_applications_jwks_column] %></dd>
      <% end %>
      <% if oauth_application[rodauth.oauth_applications_jwks_uri_column] %>
        <dt><%= rodauth.oauth_applications_jwks_uri_label %>: </dt>
        <dd><%= oauth_application[rodauth.oauth_applications_jwks_uri_column] %></dd>
      <% end %>
    <% end %>
  </dl>
</div>

app/views/rodauth/oauth_applications.html.erb
<% apps_count = rodauth.db[rodauth.oauth_applications_table].count %>
<div class="btn-group" role="group" aria-label="Buttons">
  <%= link_to "New Oauth Application",  "#{rodauth.oauth_applications_path}/new", class: "btn btn-secondary" %>
</div>
<% if apps_count.zero? %>
  <p>No oauth applications yet!</p>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Client ID (<%= apps_count %>)</th>
        <th scope="col">Name</th>
        <th scope="col">Homepage</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% rodauth.db[rodauth.oauth_applications_table].each do |application| %>
        <tr>
          <td><%= application[rodauth.oauth_applications_client_id_column] %></td>
          <td><%= application[rodauth.oauth_applications_name_column] %></td>
          <td><%= application[rodauth.oauth_applications_homepage_url_column] %></td>
          <td><%= link_to "Show",  rodauth.oauth_application_path(application[rodauth.oauth_applications_id_column]) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>